version: '3.3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'blog'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bloguser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'blogpass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./blog-db-data:/var/lib/mysql
  blog:
    platform: linux/amd64
    image: championswimmer/blogapi-apr-2023:0.0.4
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8822:8822'
    expose:
      - '8822'
